spring:
  application:
    name: springcloud-producer

server:
  port: 8003

eureka:
  instance:
    hostname: localhost # 设置主机名
    prefer-ip-address: true # 注册时使用ip而不是主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,mappings # 监控

