server:
  port: 8002
  servlet:
    context-path: /

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.241.47:8848
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    gateway:
      routes:
#        - id: route1
#          uri: https://www.baidu.com/
#          predicates:
#            - Path=/**
        - id: consumer-gateway
          uri: lb://consumer
          predicates:
            - Path=/**
#          filters:
#            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.cloud.gateway: debug
