server:
  port: 8801

eureka:
  instance:
    hostname: localhost # 设置主机名
    prefer-ip-address: true # 注册时使用ip而不是主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: route1
        uri: https://www.baidu.com/
        predicates:
          - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: debug
