server:
  port: 8001

eureka:
  instance:
    hostname: localhost # 设置主机名
    prefer-ip-address: true # 注册时使用ip而不是主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
           - Path=/test

