server:
  port: 8001

spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: admin
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.241.47:8848
        metadata:
          user.name: admin
          user.password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS