server:
  port: 8802
  servlet:
    context-path: /producer

spring:
  application:
    name: producer
  cloud:
    nacos:
      discovery:
        server-addr: 106.53.241.47:8848
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    sentinel:
      transport:
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
